# See config.example.yml for documentation.
object_base: orig/ST7P01
object: sys/main.dol
hash: 327fe0460c0b5497c5b8fe17bb4b4475b6cdeed3
symbols: config/ST7P01/symbols.txt
splits: config/ST7P01/splits.txt
ldscript_template: config/ST7P01/ldscript.tpl
mw_comment_version: 14
selfile: files/main.sel
selfile_hash: aa12a5d4cdfa93b2b16b196de986f52e78dcec17
