name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/fortunestreetmodding/boom-street-decomp-build:main

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ST7P01]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # Normalize file mod times
    - name: Restore timestamps
      run: |
        uv run https://raw.githubusercontent.com/MestreLion/git-tools/refs/tags/v2022.12/git-restore-mtime \
            --merge --commit-time

    - name: Prepare
      run: cp -a /orig .

    - name: Cache build
      uses: actions/cache@v4
      with:
        path: |
          build
          .ninja_deps
          .ninja_log
        key: ${{ runner.os }}-${{ matrix.version }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-${{ matrix.version }}-

    - name: Build
      run: |
        python configure.py --map --version ${{ matrix.version }} \
            --binutils /binutils --compilers /compilers
        ninja all_source progress build/${{ matrix.version }}/report.json

    - name: Upload map
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_maps
        path: build/${{ matrix.version }}/**/*.MAP

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_report
        path: build/${{ matrix.version }}/report.json
